### ISSUE TITLE
Unexpected character in prompt

### ISSUE THREAD

**Issue by a1375625918** [Kr1S-D/UltimateAntibotRecoded#15]
Can these CR characters in boxes at the end of the line be removed?

![Untitled](https://user-images.githubusercontent.com/87858091/210751640-40974fbc-15b4-46b0-98dd-e2eea32860cd.png)

**Comment by Kr1S-D** [comment]
U need to set the encoding of your java VM to UTF-8

**Comment by a1375625918** [comment]
I added `-Dfile.encoding=UTF-8` in the command line like this but nothing changed. 

```
java.exe -Dfile.encoding=UTF-8 -jar server.jar
```

Not sure if I'm doing the right thing.

**Comment by Kr1S-D** [comment]
use a text editor that supports that encoding like Notepad++ and not the windows editor

**Comment by a1375625918** [comment]
`messages.yml` is the default one and I haven't modified it before.

VSCode said it's already UTF-8 and I tried to switch the default CRLF eol sequence to LF. The result is the same as before.

![messages yml - Visual Studio Code 2023_1_23 9_31_34](https://user-images.githubusercontent.com/87858091/213952766-fd66fa84-3377-4170-9de8-053912ca1f62.png)

If I replace YAML list style lines with `\n`, everything goes as expected.

![messages yml - Visual Studio Code 2023_1_23 9_47_23](https://user-images.githubusercontent.com/87858091/213953403-a7d23d70-8913-4063-bd85-e905dad77b01.png)

![Minecraft_ 1 19 3 2023_1_23 9_45_46](https://user-images.githubusercontent.com/87858091/213953278-3f9e441a-7321-4af0-9c5d-09114fc04d06.png)

_BTW adding a prefix and suffix section will be easier for operator to manage title and contact information._
```yaml
prefix:
  - "&fᛃ &4&LU&c&LA&4&LB &fᛃ"
  - ""
suffix:
  - ""
  - "&cDiscord &7» &c&ndiscord.myserver.com"
  - "&c&nmc.yourserver.net"
blacklisted:
  - "&7You have been blacklisted by the &cAntibot System"
  - "&7Contact us on discord providing your &cid&7 to be able to &cplay!"
  - ""
  - "&cReason &7» &c$1"
  - "&cID &7» &c$2"
```
